#! /bin/bash

# Build the server for a machine whose CPU is older than this one. LineairDB
# compiles its release build with -march=native, so a binary built on a host
# with AVX-512 dies with SIGILL elsewhere. This swaps that flag for a baseline
# and keeps the result out of build/ so the native build stays intact.
# Override the baseline with HELIOS_PORTABLE_ARCH (default x86-64-v3: AVX2, no AVX-512).

set -euo pipefail

cd "$(dirname "$0")/.."
ROOT=$(pwd)
ARCH=${HELIOS_PORTABLE_ARCH:-x86-64-v3}
BUILD_DIR="$ROOT/build-v3/server"
WRAPPER="$ROOT/build-v3/cxx_wrapper.sh"

mkdir -p "$BUILD_DIR"

cat > "$WRAPPER" <<EOF
#! /bin/bash
# Generated by scripts/build_portable.sh
args=()
for a in "\$@"; do
  if [ "\$a" = "-march=native" ]; then args+=("-march=$ARCH"); else args+=("\$a"); fi
done
exec "${CXX:-/usr/bin/c++}" "\${args[@]}"
EOF
chmod +x "$WRAPPER"

echo "Building server for -march=$ARCH ..."
cd "$BUILD_DIR"
cmake "$ROOT/server" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_COMPILER="$WRAPPER" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=1
make -j "$(nproc)"

echo
echo "Binary: $BUILD_DIR/lineairdb-server"
echo "Copy it together with the libraries it does not find on the target:"
ldd "$BUILD_DIR/lineairdb-server" | awk '/libduckdb|libprotobuf|libjemalloc/ {print "  " $3}'
